### ISSUE TITLE
Rules with literals at beginning and end don't work

### ISSUE THREAD

**Issue by pborenstein** [Floby/node-tokenizer#5]
The tokenizer doesn't handle rules like `/^{\w+}/` to match tokens like `{this}`.

Probably related to issue #4 

See: https://gist.github.com/pborenstein/9378700

**Comment by farskipper** [comment]
Hey, I've had a similar problem. It's b/c tokenizer uses bisection to optimize matching performance. For some tokenizing problems bisection is definitely the right call, but not for all of them. For that reason I made [tokenizer2](https://www.npmjs.com/package/tokenizer2) which doesn't use bisection, and should resolve this issue.

**Comment by pborenstein** [comment]
Cool. I made a private fork (https://github.com/pborenstein/node-tokenizer) for
the project I was working on at the time, but I never published it as a
module. If you look at my version, you can see that I used a pretty ugly
brute-force approach :)

##
